#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pacman -S accountsservice arandr chromium leafpad lightdm lightdm-gtk-greeter lxpanel lxappearance-obconf lxrandr lxsession openbox obconf xfce4-panel xfce4-whiskermenu-plugin thunar thunar-archive-plugin thunar-volman gvfs ntfs-3g dosfstools zip unzip p7zip unrar ttf-liberation xdg-user-dirs xfce4-terminal networkmanager network-manager-applet xfce4-power-manager plank nitrogen xorg-xprop gparted gmrun xscreensaver numlockx gnome-disk-utility blueman xfce4-settings onboard gpicview gnome-ppp i3lock pulseaudio pulseaudio-alsa pavucontrol xdotool gtk-engines tumbler
rm -r ~/.config
rm -r ~/.local
cp -r obsession-git/.icons ~/.icons
cp -r obsession-git/.config ~/.config
cp -r obsession-git/.local ~/.local
cp obsession-git/.gtkrc-2.0 ~/.gtkrc-2.0
cp obsession-git/.gtkrc-2.0.mine ~/.gtkrc-2.0.mine
sudo cp obsession-git/yad-logout /usr/bin
sudo cp obsession-git/yad-shutdown /usr/bin
sudo cp obsession-git/plank-gui /usr/bin
sudo cp obsession-git/control_panel /usr/bin
sudo cp -r obsession-git/Control_Panel /usr/share
sudo cp -r obsession-git/wallpaper /usr/share
sudo cp -r obsession-git/Chromixium /usr/share/themes
sudo cp -r obsession-git/lightdm /etc/
sudo cp -r obsession-git/chrome-avatars /usr/share/bin
xdg-user-dirs-update
sudo systemctl enable NetworkManager
sudo systemctl enable lightdm
sudo systemctl enable accounts-daemon.service
chmod +x obsession-git/aur_ins
obsession-git/aur_ins
gtk-update-icon-cache ~/.icons/chromixium/
sudo gtk-update-icon-cache /usr/share/icons/elementary-xfce
sudo gtk-update-icon-cache /usr/share/icons/elementary-xfce-dark
sudo gtk-update-icon-cache /usr/share/icons/HighContrast
